### ISSUE TITLE
Error on player join

### ISSUE THREAD

**Issue by Frank-xy** [thebigsmileXD/PocketRadio#10]
`Server thread/CRITICAL ErrorException: "unpack(): Type I: not enough input, need 4, have 0" (EXCEPTION) in "plugins/PocketRadio.phar/src/xenialdan/PocketRadio/libs/xenialdan/libnbs/NBSFile" at line 186
`

By the way, I used the .nbs file generated by myself

**Comment by Frank-xy** [comment]
Sorry I tried the .nbs file you posted in the README.MD, but it doesn't work.

**Comment by GoodLucky777** [comment]
I have same problem too!

**Comment by inxomnyaa** [comment]
Probably the files got corrupted or something, or some format changes happened. I will check and update my nbslib

**Comment by inxomnyaa** [comment]
libnbs now supports newer .nbs file formats, and even OpenNoteBlockStudio files. Closing since resolved after rewrite.
