### ISSUE TITLE
doesnt work

### ISSUE THREAD

**Issue by jaylac2000** [thebigsmileXD/PocketRadio#12]
doesnt add any commands or plugin data

**Comment by inxomnyaa** [comment]
Have you got the poggit build?

Any errors in the console?

is the config generated?

Note at me: upgrade readme file

**Comment by ArchonKlaus** [comment]
[19:36:04] [Server thread/ERROR]: [[PocketRadio]] Class 'xenialdan\customui\windows\SimpleForm' not found
[19:36:04] [Server thread/ERROR]: [[PocketRadio]] 47

I have the customui virion installed.

**Comment by samupozzo** [comment]
ErrorException: "fopen(Smells Like Teen Spirit.nbs): failed to open stream: No such file or directory" (EXCEPTION) in "/root/HubPE/virions/libnbs-master/src/xenialdan/libnbs/NBSFile" at line 106

and the nbs file is orrible.. It sounds very bad (with zmusicbox it works perfect)

**Comment by inxomnyaa** [comment]
zmusicbox does not support multiple sounds at one tick (or to be precise: layers) sadly. It was a great inspiration when creating the plugin though.
If i remember correctly, this nbs file is really old anyways, and still uses redstone tick speed 🤷🏻‍♂️. I will try to create and add better files in the future.

> ErrorException: "fopen(Smells Like Teen Spirit.nbs): failed to open stream: No such file or directory" (EXCEPTION) in "/root/HubPE/virions/libnbs-master/src/xenialdan/libnbs/NBSFile" at line 106
I will check that out ASAP and fix it. Expect a fix for that today

**Comment by inxomnyaa** [comment]
Checked the sounds, appears the pitch is messed up 🤔

Can you check if the error still happens on the build 9? https://poggit.pmmp.io/ci/thebigsmileXD/PocketRadio/PocketRadio/dev:9

**Comment by inxomnyaa** [comment]
Closing since patched after rewrite. Pitch is now correctly calculated, fopen bug is resolved (also happened upon song selection)
