### ISSUE TITLE
how to make player all hear song without changing volume? and when i use volume 50, its not working

### ISSUE THREAD

**Issue by GuckTubeYT** [thebigsmileXD/PocketRadio#13]
how to make player all hear song without changing volume? and when i use volume 50, its not working
please help meeeee

**Comment by inxomnyaa** [comment]
illegible. Please form proper sentences and explain exactly what is wrong, or what you want. German?

**Comment by GuckTubeYT** [comment]
I am not a german, please help me, when i turn volume to 50, i cant hear

**Comment by GuckTubeYT** [comment]
And how to all new player can hear song?

**Comment by inxomnyaa** [comment]
i just fucking can't understand you

**Comment by GuckTubeYT** [comment]
Can i edit this?

public static function getSoundVolume(Player $player)
    {
        return self::getVolume($player) / 100;
    }

**Comment by inxomnyaa** [comment]
> And how to all new player can hear song?

Everyone who is on the server hears songs
> I am not a german, please help me, when i turn volume to 50, i cant hear

I will check the slider. I am sure it is correct though. Check your layer volume in the nbs file

**Comment by inxomnyaa** [comment]
> Can i edit this?


Enjoy, have fun, but it will give you totally incorrect results. (unless you return something between 0 and 1)
