### ISSUE TITLE
Class 'xenialdan\customui\windows\SimpleForm' not found

### ISSUE THREAD

**Issue by GuckTubeYT** [thebigsmileXD/PocketRadio#14]
Please How to Fix That
2019-12-26 [02:48:20] [Server thread/ERROR]: [Radio] Class 'xenialdan\customui\windows\SimpleForm' not found
2019-12-26 [02:48:20] [Server thread/ERROR]: [Radio] 49

I Just Download PocketRadio, CustomUI, and LibNBS
but still didnt work
Please help me

**Comment by GuckTubeYT** [comment]
bruh, still not responding

**Comment by Newcoolboys** [comment]
R u on 1.13?

**Comment by Newcoolboys** [comment]
are you on 1.13?

**Comment by inxomnyaa** [comment]
download phar from poggit.
