### ISSUE TITLE
Why i set volume 50, and i dont hear song?

### ISSUE THREAD

**Issue by GuckTubeYT** [thebigsmileXD/PocketRadio#16]
Please help me, Why i set volume 50, and i dont hear song?

**Comment by GuckTubeYT** [comment]
when i set volume 100, i hear song

**Comment by GuckTubeYT** [comment]
Lol, why not answered?

**Comment by inxomnyaa** [comment]
Duplicate of #13 . Stop spamming the repo. Follow the Readme instructions and check the config.yml. Merry Xmas -.-
