### ISSUE TITLE
Please update to protocol 390 / MCPE 1.14.60

### ISSUE THREAD

**Issue by eloklam** [thebigsmileXD/PocketRadio#21]
Tried to add protocol 390 in plugin.yml but it isn't working!
Maybe more than that should be changed?

**Comment by inxomnyaa** [comment]
I currently have no access to Minecraft 1.14.0.60, so i can not test the changes. I will push an update soon.

**Comment by inxomnyaa** [comment]
No more updates on PM3 plugins.
Plugin might get updated once PM4 drops (current ETA december)

**Comment by inxomnyaa** [comment]
Plugin has been updated. Protocol version check has been removed so the plugin should work fine in future versions
