### ISSUE TITLE
Request: add "/radio stop" or "/radio off" command

### ISSUE THREAD

**Issue by brokiem** [thebigsmileXD/PocketRadio#24]

**Comment by inxomnyaa** [comment]
I have implemented the `/radio pause` command which currently does this globally.
A proper pause command will be added in the future

**Comment by inxomnyaa** [comment]
Playlists are now implemented
`/radio pause` now actually pauses playback instead of stopping it.
Stopping a playlist is automatically done if no players are in a playlist, or if forced by a plugin.
Events have been added to check for the reason
