### ISSUE TITLE
Still incompatible protocol

### ISSUE THREAD

**Issue by KadTheHunter** [thebigsmileXD/PocketRadio#26]
When using the latest release (which was Dev 14) it says
`[09:56:37] [Server thread/ERROR]: Could not load plugin 'PocketRadio': Incompatible network protocol version (plugin requires one of: 388, 389)` upon trying to load the plugin.

Using Dev 15, it says 
`[09:56:37] [Server thread/ERROR]: Could not load plugin 'PocketRadio': Incompatible network protocol version (plugin requires one of: 388, 389, 390)` upon trying to load it.

Perhaps in plugin.yml it needs to be `[388, 389, 390]` with spaces rather than `[388,389]`?

**Comment by inxomnyaa** [comment]
> Perhaps in plugin.yml it needs to be [388, 389, 390] with spaces rather than [388,389]?

This is totally stupid nonsense.

I will check pmmp changelogs for changes and add support for the latest PMMP network protocol version.
