### ISSUE TITLE
Per player listen music option

### ISSUE THREAD

**Issue by IvanCraft623** [thebigsmileXD/PocketRadio#27]
I would like that there was the option for each player to listen to the music or not because in some devices causes lag.

**Comment by inxomnyaa** [comment]
Reopening, feature not implemented

**Comment by inxomnyaa** [comment]
This is currently the highest priority - At the moment all commands but `/radio volume` apply globally and are locked behind OP perms

**Comment by inxomnyaa** [comment]
In theory you could now create a plugin that implements per-player Playlist objects and listen for the LoadSongsEvent and add the songs to the player's playlist.
The commands of this plugin still only allow modifying the global server playlist though. Currently considering if this is wanted behavior.

**Comment by inxomnyaa** [comment]
The original request was about disabling the music per player - setting the volume to 0% should do this but currently doesn't
