### ISSUE TITLE
please update

### ISSUE THREAD

**Issue by jaylac2000** [thebigsmileXD/PocketRadio#30]
would like to play christmas music on my server

**Comment by inxomnyaa** [comment]
I am sorry to disappoint, but i am not updating PM3 plugins anymore

But i see you already created a PR - i can not validate if the plugin is working though

**Comment by jaylac2000** [comment]
![image](https://user-images.githubusercontent.com/53111006/101945207-ddbce780-3bbb-11eb-98aa-eddd97dcca4c.jpg)

It’s working, however if I may ask. How can I convert .mp3 files to .nbs -  I am trying to decorate my server for Christmas

**Comment by inxomnyaa** [comment]
> How can I convert .mp3 files to .nbs

Keep in mind that it is an entirely different format. 
From https://www.bearaudiotool.com/mp3-to-midi:
> Converting an MP3 file into a MIDI file is like turning a song into a score. This is not an easy task. The converted MIDI file deviates from the original sound. But it is very similar to the original music. Tones, trebles, bass, and melody are all similar. 

You can convert .midi to .nbs though. there should be some text around here https://forums.pmmp.io/threads/200-nbs-songs.294/
