### ISSUE TITLE
Class ds/map not found

### ISSUE THREAD

**Issue by SunshroomChan** [thebigsmileXD/PocketRadio#37]
It was error on libnbs\NBSFile.php on line 70
PocketMine API: 3.25.4
Operating System: Pterodactyl (Linux)
I don't know how i could fix the code/update code?

**Comment by inxomnyaa** [comment]
Enable ds in php.ini / install it.

**Comment by SunshroomChan** [comment]
Where is the php.ini ? I didn't find it on Pterodactyl File Manager

**Comment by inxomnyaa** [comment]
Sorry but i am not going to explain how the Pterodactyl File Manager File Search Box works.

**Comment by inxomnyaa** [comment]
Update:
As soon as PM4 drops, this plugin will get an update that does not use Ds
