### ISSUE TITLE
Network protocol problem 

### ISSUE THREAD

**Issue by mo-gd** [thebigsmileXD/PocketRadio#38]
Hello 👋 i have a problem with the plugin

`2021-11-30 [08:52:56] [Server thread/ERROR]: Could not load plugin 'PocketRadio': Incompatible network protocol version (plugin requires one of: 388, 389, 390, 391, 392, 393, 394, 395, 396, 397, 398, 399, 400, 401, 402, 403, 404, 405, 406, 407, 408, 409, 410, 411, 412, 413, 414, 415, 416, 417, 418, 419, 420, 421, 422)`

**Comment by inxomnyaa** [comment]
### Thank you for creating this issue.
I am currently very limited on my time and low on funds. In case you want an update / fix to be released urgently, feel free to make a donation on any of the following services:
- **Buymeacoffee**
https://www.buymeacoffee.com/XenialDan
- **PayPal Me**
https://www.paypal.me/XenialDan

Leave your name in the description of the donation and include which plugin / library you want updates for, and i will finish it within a week. Additionally you can claim the Donator rank on my Discord if you include your `@name`: `discord.gg/Vh7Usbs`
*Thank you for your generous support and have a nice day!*

**Comment by inxomnyaa** [comment]
The check has been removed entirely
