### ISSUE TITLE
PM4 support

### ISSUE THREAD

**Issue by AIPTU** [thebigsmileXD/PocketRadio#39]
Please add support for PM4

**Comment by inxomnyaa** [comment]
flagging this as duplicate of #38

**Comment by inxomnyaa** [comment]
### Thank you for creating this issue.
I am currently very limited on my time and low on funds. In case you want an update / fix to be released urgently, feel free to make a donation on any of the following services:
- **Buymeacoffee**
https://www.buymeacoffee.com/XenialDan
- **PayPal Me**
https://www.paypal.me/XenialDan

Leave your name in the description of the donation and include which plugin / library you want updates for, and i will finish it within a week. Additionally you can claim the Donator rank on my Discord if you include your `@name`: `discord.gg/Vh7Usbs`
*Thank you for your generous support and have a nice day!*
