### ISSUE TITLE
Is there any bugs still being corrected?

### ISSUE THREAD

**Issue by Cher0325** [thebigsmileXD/PocketRadio#43]
Error: "Class "xenialdan\libnbs\NBSFile" not found" (EXCEPTION) in "/root/DN/plugins/PocketRadio-master/src/xenialdan/PocketRadio/Loader" at line 66
--- Stack trace ---
  #0 pmsrc/src/scheduler/AsyncTask(90): pocketmine\scheduler\AsyncTask@anonymous/root/DN/plugins/PocketRadio-master/src/xenialdan/PocketRadio/Loader.php:46$938->onRun()
  #1 (): pocketmine\scheduler\AsyncTask->run()

**Comment by inxomnyaa** [comment]
Run the compiled version or install the libnbs virion https://github.com/thebigsmileXD/libnbs/
