### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by MohamadRZ4** [thebigsmileXD/PocketRadio#47]
TypeError: "CortexPE\Commando\BaseSubCommand::__construct(): Argument #1 ($name) must be of type string, xenialdan\PocketRadio\Loader given, called in C:\Users\LENOVO\Desktop\test\plugins\PocketRadio-master\src\xenialdan\PocketRadio\commands\RadioCommand.php on line 18" (EXCEPTION) in "C:/Users/LENOVO/Desktop/test/virions/Commando_dev-4.phar/src/CortexPE/Commando/BaseSubCommand" at line 60
--- Stack trace ---
  #0 plugins/PocketRadio-master/src/xenialdan/PocketRadio/commands/RadioCommand(18): CortexPE\Commando\BaseSubCommand->__construct(object xenialdan\PocketRadio\Loader#46087, string[6] volume)
  #1 C:/Users/LENOVO/Desktop/test/virions/Commando_dev-4.phar/src/CortexPE/Commando/BaseCommand(89): xenialdan\PocketRadio\commands\RadioCommand->prepare()
  #2 plugins/PocketRadio-master/src/xenialdan/PocketRadio/Loader(48): CortexPE\Commando\BaseCommand->__construct(object xenialdan\PocketRadio\Loader#46087, string[5] radio)
  #3 pmsrc/src/plugin/PluginBase(119): xenialdan\PocketRadio\Loader->onEnable()
  #4 pmsrc/src/plugin/PluginManager(454): pocketmine\plugin\PluginBase->onEnableStateChange(true)
  #5 pmsrc/src/Server(1446): pocketmine\plugin\PluginManager->enablePlugin(object xenialdan\PocketRadio\Loader#46087)
  #6 pmsrc/src/Server(1074): pocketmine\Server->enablePlugins(object pocketmine\plugin\PluginEnableOrder#45915)
  #7 pmsrc/src/PocketMine(341): pocketmine\Server->__construct(object pocketmine\thread\ThreadSafeClassLoader#4, object pocketmine\utils\MainLogger#6, string[29] C:\Users\LENOVO\Desktop\test\, string[37] C:\Users\LENOVO\Desktop\test\plugins\)

**Comment by inxomnyaa** [comment]
Did this happen on the compiled poggit phar?

**Comment by inxomnyaa** [comment]
Did this happen on the compiled poggit phar?
