### ISSUE TITLE
Add Plz

### ISSUE THREAD

**Issue by gamegam** [thebigsmileXD/PocketRadio#51]
Is it possible to listen to mp3 or ogg

**Comment by inxomnyaa** [comment]
Use resource packs and playsoundpacket for that.. the nbs format can support custom notes, but not full songs.

**Comment by gamegam** [comment]
Please implement it.

**Comment by inxomnyaa** [comment]
As i said - playing ogg or mp3 is not in the scope of this plugin. nbs files already have this. Closing
